### PR TITLE
Add 'Past visit' table

### PR DESCRIPTION
**Pull request by straylightlabs**

### CODE REVIEW

**Comment by straylightlabs** [comment]
@tajftw  Should we still have "Actions" column for Past visit table?

**Comment by tajftw** [comment]
@skywhale there should still be actions to 'Duplicate' (create a new event for the same guest with a different date and time) and 'Edit' (modify the old event in case it was missed and the date simply needs to be moved forward).

**Comment by straylightlabs** [comment]
@tajftw thanks. "duplicate" sounds like a new feature request, so here it is. https://app.asana.com/0/260679654120467/302232833758142

I added back "edit" link. Please give LGTM if it looks good.

**Comment by straylightlabs** [comment]
The demo server is up running at:
https://straylight.jp/connect-dev

you may need to logout and in again. reusing the same credential you obtained from prod server may not work.

**Comment by skywhale** [comment]
BTW I should switch back to "skywhale" :)

**Comment by skywhale** [comment]
@tajftw I'll go ahead and merge. Plz feel free to let me know if you have issues or concerns.

**Pull request merged**
